### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by rmichela** [rmichela/ZombiePlague#1]
12:14:28 PM [SEVERE] Could not pass event PlayerInteractEvent to ZombiePlague org.bukkit.event.EventException at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477) at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462) at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:177) at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:287) at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:637) at net.minecraft.server.Packet15Place.handle(SourceFile:39) at net.minecraft.server.NetworkManager.b(NetworkManager.java:229) at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:114) at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:172) at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83) at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:569) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:461) at net.minecraft.server.ThreadServerApplication.run(SourceFile:492) Caused by: java.lang.NullPointerException at com.ryanmichela.tsZombiePlague.SugarEatListener.onPlayerInteract(SugarEatListener.java:58) at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ... 14 more

**Comment by rmichela** [comment]
Fixed
